// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqUser struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUser) Reset()         { *m = ReqUser{} }
func (m *ReqUser) String() string { return proto.CompactTextString(m) }
func (*ReqUser) ProtoMessage()    {}
func (*ReqUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ReqUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUser.Unmarshal(m, b)
}
func (m *ReqUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUser.Marshal(b, m, deterministic)
}
func (m *ReqUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUser.Merge(m, src)
}
func (m *ReqUser) XXX_Size() int {
	return xxx_messageInfo_ReqUser.Size(m)
}
func (m *ReqUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUser proto.InternalMessageInfo

func (m *ReqUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqUser) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type ResUser struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResUser) Reset()         { *m = ResUser{} }
func (m *ResUser) String() string { return proto.CompactTextString(m) }
func (*ResUser) ProtoMessage()    {}
func (*ResUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ResUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResUser.Unmarshal(m, b)
}
func (m *ResUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResUser.Marshal(b, m, deterministic)
}
func (m *ResUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResUser.Merge(m, src)
}
func (m *ResUser) XXX_Size() int {
	return xxx_messageInfo_ResUser.Size(m)
}
func (m *ResUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ResUser.DiscardUnknown(m)
}

var xxx_messageInfo_ResUser proto.InternalMessageInfo

func (m *ResUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqUser)(nil), "proto.ReqUser")
	proto.RegisterType((*ResUser)(nil), "proto.ResUser")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xe6, 0x5c, 0xec, 0x41, 0xa9,
	0x85, 0xa1, 0xc5, 0xa9, 0x45, 0x42, 0x52, 0x5c, 0x1c, 0x20, 0x3a, 0x2f, 0x31, 0x37, 0x55, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x17, 0x12, 0xe0, 0x62, 0x0e, 0x28, 0x4f, 0x91, 0x60,
	0x02, 0x0b, 0x83, 0x98, 0x4a, 0xaa, 0x20, 0x8d, 0xc5, 0x84, 0x34, 0x1a, 0x65, 0x72, 0xf1, 0x78,
	0xa4, 0xe6, 0xe4, 0xe4, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xe9, 0x71, 0x71, 0x39,
	0x17, 0xa5, 0x26, 0x96, 0xa4, 0x82, 0x75, 0xf2, 0x41, 0x1c, 0xa3, 0x07, 0x75, 0x82, 0x14, 0x82,
	0x0f, 0x36, 0x59, 0x89, 0x41, 0x48, 0x93, 0x8b, 0xd5, 0x27, 0x3f, 0x3d, 0x33, 0x8f, 0xb0, 0xd2,
	0x24, 0x36, 0xb0, 0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xa8, 0x46, 0x25, 0xe6, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	CreateUser(ctx context.Context, in *ReqUser, opts ...grpc.CallOption) (*ResUser, error)
	Login(ctx context.Context, in *ReqUser, opts ...grpc.CallOption) (*ResUser, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) CreateUser(ctx context.Context, in *ReqUser, opts ...grpc.CallOption) (*ResUser, error) {
	out := new(ResUser)
	err := c.cc.Invoke(ctx, "/proto.HelloService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) Login(ctx context.Context, in *ReqUser, opts ...grpc.CallOption) (*ResUser, error) {
	out := new(ResUser)
	err := c.cc.Invoke(ctx, "/proto.HelloService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	CreateUser(context.Context, *ReqUser) (*ResUser, error)
	Login(context.Context, *ReqUser) (*ResUser, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) CreateUser(ctx context.Context, req *ReqUser) (*ResUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedHelloServiceServer) Login(ctx context.Context, req *ReqUser) (*ResUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HelloService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).CreateUser(ctx, req.(*ReqUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HelloService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Login(ctx, req.(*ReqUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _HelloService_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _HelloService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
